### ISSUE TITLE
Data for Grounded Event-Sequence Modeling

### ISSUE THREAD

**Issue by yeliudev** [DCDmllm/Momentor#3]
Hi @longqian-zju, thanks for sharing this work. I was wondering whether you are using the same videos and annotations for Grounded Event-Sequence Modeling and instruction tuning. The paper did not mention what data (and the size) you used for GESM.

**Comment by yeliudev** [comment]
Thanks for your reply! Could you please share the GESM annotations as well? It seems that the existing annotations are only for instruction tuning.

**Comment by longqian-zju** [comment]
We have provided the data and script for GESM annotations. Please refer to the updated readme file for the details.
