### ISSUE TITLE
load_video function

### ISSUE THREAD

**Issue by nguyentthong** [DCDmllm/Momentor#5]
Hi @loveofguoke @longqian-zju,

Thank you for your interesting work. I have been really excited about it!

When I run your training script, I encounter this error:

```
ModuleNotFoundError: No module named 'momentor.eval'
```

Can you help me locate where the momentor.eval folder is?

Thank you so much!

**Comment by anilbatra2185** [comment]
hi @longqian-zju ,

I would really appreciate if you can share the missing files.

Thanks

**Comment by longqian-zju** [comment]
> Hi @loveofguoke @longqian-zju,
> 
> Thank you for your interesting work. I have been really excited about it!
> 
> When I run your training script, I encounter this error:
> 
> ```
> ModuleNotFoundError: No module named 'momentor.eval'
> ```
> 
> Can you help me locate where the momentor.eval folder is?
> 
> Thank you so much!

Sorry, we check the code and find that this function is in fact not used, thus we delete it.

The `eval` folder can be found in the repository of [Video-ChatGPT](https://github.com/mbzuai-oryx/Video-ChatGPT) if you find that necessary. Sorry for the inconvenience we have caused.
