### ISSUE TITLE
Correct dataset format to train the model?

### ISSUE THREAD

**Issue by anilbatra2185** [DCDmllm/Momentor#7]
Hi @longqian-zju , @loveofguoke 

I am trying to train the model, however, the dataset before and after conversion has different formats and both the formats seems in-compatible to train the model.

```
data_0 = json.load(open("Moment-10M_0.json"))
data_0["jS2fE622RMA"]["qa_data"]
```
> [{'id': 'jS2fE622RMA', 'data_type': 'qa_data', 'variables': {'moment': [0.0, 12.4]}, 'conversations': [{'User': 'Please watch the clip of {moment}. What color is the car with a black stripe?', 'Assistant': 'The car with a black stripe is a black car.'}], 'clip_similarity': 0.2374267578125}, {'id': 'jS2fE622RMA', 'data_type': 'qa_data', 'variables': {'moment': [12.4, 14.233333333333333]}, 'conversations': [{'User': 'Take a look at the segment of {moment}. What is the color of the SUV in the parking lot?', 'Assistant': 'The color of the SUV in the parking lot is blue.'}]

The code in the [train_momentor.py](https://github.com/DCDmllm/Momentor/blob/3c248959910ff5b22eca14d9be549f58151c931f/momentor/train/train_momentor.py#L280) creates new format, however, the key `prototype` or `backbone` do not exist. 
```
qa_types = ['qa_data', 'instance_qa_data', 'cross_segment_qa_data']
packed_instruction_data = []
for video_name in tqdm(instruction_data):
    for key in instruction_data[video_name]:
        for dialogue in instruction_data[video_name][key]:
            text_dialogue = dialogue['dialogue']
            backbone = dialogue['prototype']['backbone']
            if key in qa_types:
                backbone[0]['User'] = re.sub(r'(' + re.escape(sent_tokenize(text_dialogue[0]['User'])[0]) + r') +', '', backbone[0]['User'])
            packed_instruction_data.append({
                'id' : video_name,
                'data_type' : key,
                'moment' : dialogue['prototype']['variables'].get('moment', None),
                'click_position' : dialogue['prototype']['variables'].get('click_position', None),
                'instance_class' : dialogue['prototype']['variables'].get('instance_class', None),
                'SOURCE_CLIP' : dialogue['prototype']['variables'].get('SOURCE_CLIP', None),
                'content' : dialogue['prototype']['variables'].get('content', None),
                'conversations' : backbone,
            })
```

Lastly, the `packed_instruction_data` format of data is not being used in the file [train_momentor.py](https://github.com/DCDmllm/Momentor/blob/3c248959910ff5b22eca14d9be549f58151c931f/momentor/train/train_momentor.py).  I would appreciate if you help to resolve these issues.

**Query 2:** Do we use only data from `['qa_data', 'instance_qa_data', 'cross_segment_qa_data']` types to train the model and ignore the others?

Thanks!

**Comment by longqian-zju** [comment]
Sorry for the inconvenience we have caused. We have modified the code and fixed the wrong codes.

As for the training data, we use all types of data for more comprehensive training. Checkpoints trained using special types of data may have better performance in certain tasks.
