### ISSUE TITLE
Request for Release of Instance-Event Metric Data

### ISSUE THREAD

**Issue by appletea233** [DCDmllm/Momentor#9]
Dear Maintainers,

I hope this message finds you well. I am reaching out to inquire about the instance-event metric data used in your project.

Your work has been a great source of inspiration for my own research, and having access to the instance-event metric data would significantly aid in understanding and replicating your results.

Are there any plans to release this data in the near future? I believe it would be an invaluable resource for the community and would greatly appreciate your consideration.

Thank you for your time and efforts on this project.

Best Regards

**Comment by longqian-zju** [comment]
Sorry, as the instance-event matrix data is more of an intermediate result, we did not save it. Thank you for your interest in our work!
